# Generated by Django 2.2.5 on 2020-01-12 22:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nanapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupe',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='groupe',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
