# Generated by Django 2.2.5 on 2020-01-19 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanapp', '0003_auto_20200118_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='decompte',
        ),
    ]
