# Generated by Django 2.2.5 on 2020-01-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanapp', '0004_remove_qrcode_decompte'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_admin',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='titre_slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
